window.esdocSearchIndex = [
  [
    "cloudevent.js/src/validator.js~validator",
    "class/src/validator.js~Validator.html",
    "<span>Validator</span> <span class=\"search-result-import-path\">cloudevent.js/src/validator.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/validator.js",
    "file/src/validator.js.html",
    "src/validator.js",
    "file"
  ],
  [
    "src/validator.js~validator#[symbol.tostringtag]",
    "class/src/validator.js~Validator.html#instance-get-[Symbol.toStringTag]",
    "src/validator.js~Validator#[Symbol.toStringTag]",
    "member"
  ],
  [
    "src/validator.js~validator#constructor",
    "class/src/validator.js~Validator.html#instance-constructor-constructor",
    "src/validator.js~Validator#constructor",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisclass",
    "class/src/validator.js~Validator.html#static-method-ensureIsClass",
    "src/validator.js~Validator.ensureIsClass",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisdate",
    "class/src/validator.js~Validator.html#static-method-ensureIsDate",
    "src/validator.js~Validator.ensureIsDate",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisdatepast",
    "class/src/validator.js~Validator.html#static-method-ensureIsDatePast",
    "src/validator.js~Validator.ensureIsDatePast",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisfunction",
    "class/src/validator.js~Validator.html#static-method-ensureIsFunction",
    "src/validator.js~Validator.ensureIsFunction",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisobjectorcollection",
    "class/src/validator.js~Validator.html#static-method-ensureIsObjectOrCollection",
    "src/validator.js~Validator.ensureIsObjectOrCollection",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisobjectorcollectionnotstring",
    "class/src/validator.js~Validator.html#static-method-ensureIsObjectOrCollectionNotString",
    "src/validator.js~Validator.ensureIsObjectOrCollectionNotString",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisstring",
    "class/src/validator.js~Validator.html#static-method-ensureIsString",
    "src/validator.js~Validator.ensureIsString",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisstringnotempty",
    "class/src/validator.js~Validator.html#static-method-ensureIsStringNotEmpty",
    "src/validator.js~Validator.ensureIsStringNotEmpty",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisuri",
    "class/src/validator.js~Validator.html#static-method-ensureIsURI",
    "src/validator.js~Validator.ensureIsURI",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisversion",
    "class/src/validator.js~Validator.html#static-method-ensureIsVersion",
    "src/validator.js~Validator.ensureIsVersion",
    "method"
  ],
  [
    "src/validator.js~validator.getsize",
    "class/src/validator.js~Validator.html#static-method-getSize",
    "src/validator.js~Validator.getSize",
    "method"
  ],
  [
    "src/validator.js~validator.isarray",
    "class/src/validator.js~Validator.html#static-method-isArray",
    "src/validator.js~Validator.isArray",
    "method"
  ],
  [
    "src/validator.js~validator.isboolean",
    "class/src/validator.js~Validator.html#static-method-isBoolean",
    "src/validator.js~Validator.isBoolean",
    "method"
  ],
  [
    "src/validator.js~validator.isclass",
    "class/src/validator.js~Validator.html#static-method-isClass",
    "src/validator.js~Validator.isClass",
    "method"
  ],
  [
    "src/validator.js~validator.isdate",
    "class/src/validator.js~Validator.html#static-method-isDate",
    "src/validator.js~Validator.isDate",
    "method"
  ],
  [
    "src/validator.js~validator.isdatepast",
    "class/src/validator.js~Validator.html#static-method-isDatePast",
    "src/validator.js~Validator.isDatePast",
    "method"
  ],
  [
    "src/validator.js~validator.isdatevalid",
    "class/src/validator.js~Validator.html#static-method-isDateValid",
    "src/validator.js~Validator.isDateValid",
    "method"
  ],
  [
    "src/validator.js~validator.isdefinedandnotnull",
    "class/src/validator.js~Validator.html#static-method-isDefinedAndNotNull",
    "src/validator.js~Validator.isDefinedAndNotNull",
    "method"
  ],
  [
    "src/validator.js~validator.isfunction",
    "class/src/validator.js~Validator.html#static-method-isFunction",
    "src/validator.js~Validator.isFunction",
    "method"
  ],
  [
    "src/validator.js~validator.iskeyedcollection",
    "class/src/validator.js~Validator.html#static-method-isKeyedCollection",
    "src/validator.js~Validator.isKeyedCollection",
    "method"
  ],
  [
    "src/validator.js~validator.isnull",
    "class/src/validator.js~Validator.html#static-method-isNull",
    "src/validator.js~Validator.isNull",
    "method"
  ],
  [
    "src/validator.js~validator.isnumber",
    "class/src/validator.js~Validator.html#static-method-isNumber",
    "src/validator.js~Validator.isNumber",
    "method"
  ],
  [
    "src/validator.js~validator.isobject",
    "class/src/validator.js~Validator.html#static-method-isObject",
    "src/validator.js~Validator.isObject",
    "method"
  ],
  [
    "src/validator.js~validator.isobjectorcollection",
    "class/src/validator.js~Validator.html#static-method-isObjectOrCollection",
    "src/validator.js~Validator.isObjectOrCollection",
    "method"
  ],
  [
    "src/validator.js~validator.isobjectorcollectionnotstring",
    "class/src/validator.js~Validator.html#static-method-isObjectOrCollectionNotString",
    "src/validator.js~Validator.isObjectOrCollectionNotString",
    "method"
  ],
  [
    "src/validator.js~validator.isstring",
    "class/src/validator.js~Validator.html#static-method-isString",
    "src/validator.js~Validator.isString",
    "method"
  ],
  [
    "src/validator.js~validator.isstringnotempty",
    "class/src/validator.js~Validator.html#static-method-isStringNotEmpty",
    "src/validator.js~Validator.isStringNotEmpty",
    "method"
  ],
  [
    "src/validator.js~validator.isuri",
    "class/src/validator.js~Validator.html#static-method-isURI",
    "src/validator.js~Validator.isURI",
    "method"
  ],
  [
    "src/validator.js~validator.isundefined",
    "class/src/validator.js~Validator.html#static-method-isUndefined",
    "src/validator.js~Validator.isUndefined",
    "method"
  ],
  [
    "src/validator.js~validator.isundefinedornull",
    "class/src/validator.js~Validator.html#static-method-isUndefinedOrNull",
    "src/validator.js~Validator.isUndefinedOrNull",
    "method"
  ],
  [
    "src/validator.js~validator.isversion",
    "class/src/validator.js~Validator.html#static-method-isVersion",
    "src/validator.js~Validator.isVersion",
    "method"
  ]
]