window.esdocSearchIndex = [
  [
    "cloudevent/src/cloudevent.js~cloudevent",
    "class/src/cloudevent.js~CloudEvent.html",
    "<span>CloudEvent</span> <span class=\"search-result-import-path\">cloudevent/src/cloudevent.js</span>",
    "class"
  ],
  [
    "cloudevent/src/transformer.js~transformer",
    "class/src/transformer.js~Transformer.html",
    "<span>Transformer</span> <span class=\"search-result-import-path\">cloudevent/src/transformer.js</span>",
    "class"
  ],
  [
    "cloudevent/src/validator.js~validator",
    "class/src/validator.js~Validator.html",
    "<span>Validator</span> <span class=\"search-result-import-path\">cloudevent/src/validator.js</span>",
    "class"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/validator.test.js.html#lineNumber42",
    "create CloudEvent instances with different class hierarchy, and ensure the validation is right",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/cloudevent.test.js.html#lineNumber287",
    "create CloudEvent instances with different kind of data attribute, and ensure the validation is right",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/cloudevent.test.js.html#lineNumber77",
    "create some CloudEvent instances (empty, without minimal arguments set or not set) and ensure they are different objects",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/cloudevent.test.js.html#lineNumber117",
    "create some CloudEvent instances (with minimal fields set) and ensure they are different objects",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/cloudevent.test.js.html#lineNumber238",
    "create two CloudEvent instances with all arguments (mandatory and optional arguments) and ensure they are different objects",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/cloudevent.test.js.html#lineNumber22",
    "ensure CloudEvent class (and related Validator and Transformer classes) are exported by the library",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/cloudevent.test.js.html#lineNumber464",
    "ensure a CloudEvent/subclass instance is seen as a CloudEvent instance, but not other objects",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber324",
    "ensure dumpObject works in the right way",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber199",
    "ensure errors are transformed into data attribute in the right way",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/cloudevent.test.js.html#lineNumber60",
    "ensure isValid and validate works good on undefined and null objects",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/index.test.js.html#lineNumber22",
    "ensure objects exported by index script, exists and are of the right type",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber344",
    "ensure process info are transformed into data attribute in the right way",
    "test"
  ],
  [
    "cloudevent src/cloudevent.js~cloudevent,cloudevent",
    "test-file/test/validator.test.js.html#lineNumber119",
    "ensure some (less used) validation functions are right",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber22",
    "ensure the Transformer class (direct reference to it) works good",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber46",
    "ensure the Transformer class is good and expose some functions to transform timestamps",
    "test"
  ],
  [
    "validator src/validator.js~validator,validator",
    "test-file/test/validator.test.js.html#lineNumber22",
    "ensure the Validator class (direct reference to it) works good",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber176",
    "ensure the current timestamp is transformed to string and back as date in the right way",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber116",
    "ensure timestamps are transformed from string in the right way",
    "test"
  ],
  [
    "transformer src/transformer.js~transformer,transformer",
    "test-file/test/transformer.test.js.html#lineNumber66",
    "ensure timestamps are transformed to string in the right way",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/cloudevent.js",
    "file/src/cloudevent.js.html",
    "src/cloudevent.js",
    "file"
  ],
  [
    "src/cloudevent.js~cloudevent#[symbol.tostringtag]",
    "class/src/cloudevent.js~CloudEvent.html#instance-get-[Symbol.toStringTag]",
    "src/cloudevent.js~CloudEvent#[Symbol.toStringTag]",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#cloudeventsversion",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-cloudEventsVersion",
    "src/cloudevent.js~CloudEvent#cloudEventsVersion",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#constructor",
    "class/src/cloudevent.js~CloudEvent.html#instance-constructor-constructor",
    "src/cloudevent.js~CloudEvent#constructor",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent#contenttype",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-contentType",
    "src/cloudevent.js~CloudEvent#contentType",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#data",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-data",
    "src/cloudevent.js~CloudEvent#data",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#eventid",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-eventID",
    "src/cloudevent.js~CloudEvent#eventID",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#eventtime",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-eventTime",
    "src/cloudevent.js~CloudEvent#eventTime",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#eventtype",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-eventType",
    "src/cloudevent.js~CloudEvent#eventType",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#eventtypeversion",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-eventTypeVersion",
    "src/cloudevent.js~CloudEvent#eventTypeVersion",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#extensions",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-extensions",
    "src/cloudevent.js~CloudEvent#extensions",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#isstrict",
    "class/src/cloudevent.js~CloudEvent.html#instance-get-isStrict",
    "src/cloudevent.js~CloudEvent#isStrict",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#isvalid",
    "class/src/cloudevent.js~CloudEvent.html#instance-method-isValid",
    "src/cloudevent.js~CloudEvent#isValid",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent#payload",
    "class/src/cloudevent.js~CloudEvent.html#instance-get-payload",
    "src/cloudevent.js~CloudEvent#payload",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#schema",
    "class/src/cloudevent.js~CloudEvent.html#instance-get-schema",
    "src/cloudevent.js~CloudEvent#schema",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#schemaurl",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-schemaURL",
    "src/cloudevent.js~CloudEvent#schemaURL",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#serialize",
    "class/src/cloudevent.js~CloudEvent.html#instance-method-serialize",
    "src/cloudevent.js~CloudEvent#serialize",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent#source",
    "class/src/cloudevent.js~CloudEvent.html#instance-member-source",
    "src/cloudevent.js~CloudEvent#source",
    "member"
  ],
  [
    "src/cloudevent.js~cloudevent#tostring",
    "class/src/cloudevent.js~CloudEvent.html#instance-method-toString",
    "src/cloudevent.js~CloudEvent#toString",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent#validate",
    "class/src/cloudevent.js~CloudEvent.html#instance-method-validate",
    "src/cloudevent.js~CloudEvent#validate",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.contenttypedefault",
    "class/src/cloudevent.js~CloudEvent.html#static-method-contentTypeDefault",
    "src/cloudevent.js~CloudEvent.contentTypeDefault",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.deserializeevent",
    "class/src/cloudevent.js~CloudEvent.html#static-method-deserializeEvent",
    "src/cloudevent.js~CloudEvent.deserializeEvent",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.getjsonschema",
    "class/src/cloudevent.js~CloudEvent.html#static-method-getJSONSchema",
    "src/cloudevent.js~CloudEvent.getJSONSchema",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.iscloudevent",
    "class/src/cloudevent.js~CloudEvent.html#static-method-isCloudEvent",
    "src/cloudevent.js~CloudEvent.isCloudEvent",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.isstrictevent",
    "class/src/cloudevent.js~CloudEvent.html#static-method-isStrictEvent",
    "src/cloudevent.js~CloudEvent.isStrictEvent",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.isvalidevent",
    "class/src/cloudevent.js~CloudEvent.html#static-method-isValidEvent",
    "src/cloudevent.js~CloudEvent.isValidEvent",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.mediatype",
    "class/src/cloudevent.js~CloudEvent.html#static-method-mediaType",
    "src/cloudevent.js~CloudEvent.mediaType",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.serializeevent",
    "class/src/cloudevent.js~CloudEvent.html#static-method-serializeEvent",
    "src/cloudevent.js~CloudEvent.serializeEvent",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.validateevent",
    "class/src/cloudevent.js~CloudEvent.html#static-method-validateEvent",
    "src/cloudevent.js~CloudEvent.validateEvent",
    "method"
  ],
  [
    "src/cloudevent.js~cloudevent.version",
    "class/src/cloudevent.js~CloudEvent.html#static-method-version",
    "src/cloudevent.js~CloudEvent.version",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/transformer.js",
    "file/src/transformer.js.html",
    "src/transformer.js",
    "file"
  ],
  [
    "src/transformer.js~transformer#[symbol.tostringtag]",
    "class/src/transformer.js~Transformer.html#instance-get-[Symbol.toStringTag]",
    "src/transformer.js~Transformer#[Symbol.toStringTag]",
    "member"
  ],
  [
    "src/transformer.js~transformer#constructor",
    "class/src/transformer.js~Transformer.html#instance-constructor-constructor",
    "src/transformer.js~Transformer#constructor",
    "method"
  ],
  [
    "src/transformer.js~transformer.dumpobject",
    "class/src/transformer.js~Transformer.html#static-method-dumpObject",
    "src/transformer.js~Transformer.dumpObject",
    "method"
  ],
  [
    "src/transformer.js~transformer.errortodata",
    "class/src/transformer.js~Transformer.html#static-method-errorToData",
    "src/transformer.js~Transformer.errorToData",
    "method"
  ],
  [
    "src/transformer.js~transformer.processinfotodata",
    "class/src/transformer.js~Transformer.html#static-method-processInfoToData",
    "src/transformer.js~Transformer.processInfoToData",
    "method"
  ],
  [
    "src/transformer.js~transformer.timestampfromstring",
    "class/src/transformer.js~Transformer.html#static-method-timestampFromString",
    "src/transformer.js~Transformer.timestampFromString",
    "method"
  ],
  [
    "src/transformer.js~transformer.timestamptostring",
    "class/src/transformer.js~Transformer.html#static-method-timestampToString",
    "src/transformer.js~Transformer.timestampToString",
    "method"
  ],
  [
    "src/transformer.js~transformer.timezoneoffsetmsec",
    "class/src/transformer.js~Transformer.html#static-get-timezoneOffsetMsec",
    "src/transformer.js~Transformer.timezoneOffsetMsec",
    "member"
  ],
  [
    "src/validator.js",
    "file/src/validator.js.html",
    "src/validator.js",
    "file"
  ],
  [
    "src/validator.js~validator#[symbol.tostringtag]",
    "class/src/validator.js~Validator.html#instance-get-[Symbol.toStringTag]",
    "src/validator.js~Validator#[Symbol.toStringTag]",
    "member"
  ],
  [
    "src/validator.js~validator#constructor",
    "class/src/validator.js~Validator.html#instance-constructor-constructor",
    "src/validator.js~Validator#constructor",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisboolean",
    "class/src/validator.js~Validator.html#static-method-ensureIsBoolean",
    "src/validator.js~Validator.ensureIsBoolean",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisclass",
    "class/src/validator.js~Validator.html#static-method-ensureIsClass",
    "src/validator.js~Validator.ensureIsClass",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisdate",
    "class/src/validator.js~Validator.html#static-method-ensureIsDate",
    "src/validator.js~Validator.ensureIsDate",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisdatefuture",
    "class/src/validator.js~Validator.html#static-method-ensureIsDateFuture",
    "src/validator.js~Validator.ensureIsDateFuture",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisdatepast",
    "class/src/validator.js~Validator.html#static-method-ensureIsDatePast",
    "src/validator.js~Validator.ensureIsDatePast",
    "method"
  ],
  [
    "src/validator.js~validator.ensureiserror",
    "class/src/validator.js~Validator.html#static-method-ensureIsError",
    "src/validator.js~Validator.ensureIsError",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisfunction",
    "class/src/validator.js~Validator.html#static-method-ensureIsFunction",
    "src/validator.js~Validator.ensureIsFunction",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisnull",
    "class/src/validator.js~Validator.html#static-method-ensureIsNull",
    "src/validator.js~Validator.ensureIsNull",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisobjectorcollection",
    "class/src/validator.js~Validator.html#static-method-ensureIsObjectOrCollection",
    "src/validator.js~Validator.ensureIsObjectOrCollection",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisobjectorcollectionnotstring",
    "class/src/validator.js~Validator.html#static-method-ensureIsObjectOrCollectionNotString",
    "src/validator.js~Validator.ensureIsObjectOrCollectionNotString",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisstring",
    "class/src/validator.js~Validator.html#static-method-ensureIsString",
    "src/validator.js~Validator.ensureIsString",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisstringnotempty",
    "class/src/validator.js~Validator.html#static-method-ensureIsStringNotEmpty",
    "src/validator.js~Validator.ensureIsStringNotEmpty",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisuri",
    "class/src/validator.js~Validator.html#static-method-ensureIsURI",
    "src/validator.js~Validator.ensureIsURI",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisundefined",
    "class/src/validator.js~Validator.html#static-method-ensureIsUndefined",
    "src/validator.js~Validator.ensureIsUndefined",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisundefinedornull",
    "class/src/validator.js~Validator.html#static-method-ensureIsUndefinedOrNull",
    "src/validator.js~Validator.ensureIsUndefinedOrNull",
    "method"
  ],
  [
    "src/validator.js~validator.ensureisversion",
    "class/src/validator.js~Validator.html#static-method-ensureIsVersion",
    "src/validator.js~Validator.ensureIsVersion",
    "method"
  ],
  [
    "src/validator.js~validator.getsize",
    "class/src/validator.js~Validator.html#static-method-getSize",
    "src/validator.js~Validator.getSize",
    "method"
  ],
  [
    "src/validator.js~validator.isarray",
    "class/src/validator.js~Validator.html#static-method-isArray",
    "src/validator.js~Validator.isArray",
    "method"
  ],
  [
    "src/validator.js~validator.isboolean",
    "class/src/validator.js~Validator.html#static-method-isBoolean",
    "src/validator.js~Validator.isBoolean",
    "method"
  ],
  [
    "src/validator.js~validator.isclass",
    "class/src/validator.js~Validator.html#static-method-isClass",
    "src/validator.js~Validator.isClass",
    "method"
  ],
  [
    "src/validator.js~validator.isdate",
    "class/src/validator.js~Validator.html#static-method-isDate",
    "src/validator.js~Validator.isDate",
    "method"
  ],
  [
    "src/validator.js~validator.isdatefuture",
    "class/src/validator.js~Validator.html#static-method-isDateFuture",
    "src/validator.js~Validator.isDateFuture",
    "method"
  ],
  [
    "src/validator.js~validator.isdatepast",
    "class/src/validator.js~Validator.html#static-method-isDatePast",
    "src/validator.js~Validator.isDatePast",
    "method"
  ],
  [
    "src/validator.js~validator.isdatevalid",
    "class/src/validator.js~Validator.html#static-method-isDateValid",
    "src/validator.js~Validator.isDateValid",
    "method"
  ],
  [
    "src/validator.js~validator.isdefinedandnotnull",
    "class/src/validator.js~Validator.html#static-method-isDefinedAndNotNull",
    "src/validator.js~Validator.isDefinedAndNotNull",
    "method"
  ],
  [
    "src/validator.js~validator.iserror",
    "class/src/validator.js~Validator.html#static-method-isError",
    "src/validator.js~Validator.isError",
    "method"
  ],
  [
    "src/validator.js~validator.isfunction",
    "class/src/validator.js~Validator.html#static-method-isFunction",
    "src/validator.js~Validator.isFunction",
    "method"
  ],
  [
    "src/validator.js~validator.iskeyedcollection",
    "class/src/validator.js~Validator.html#static-method-isKeyedCollection",
    "src/validator.js~Validator.isKeyedCollection",
    "method"
  ],
  [
    "src/validator.js~validator.isnull",
    "class/src/validator.js~Validator.html#static-method-isNull",
    "src/validator.js~Validator.isNull",
    "method"
  ],
  [
    "src/validator.js~validator.isnumber",
    "class/src/validator.js~Validator.html#static-method-isNumber",
    "src/validator.js~Validator.isNumber",
    "method"
  ],
  [
    "src/validator.js~validator.isobject",
    "class/src/validator.js~Validator.html#static-method-isObject",
    "src/validator.js~Validator.isObject",
    "method"
  ],
  [
    "src/validator.js~validator.isobjectorcollection",
    "class/src/validator.js~Validator.html#static-method-isObjectOrCollection",
    "src/validator.js~Validator.isObjectOrCollection",
    "method"
  ],
  [
    "src/validator.js~validator.isobjectorcollectionnotstring",
    "class/src/validator.js~Validator.html#static-method-isObjectOrCollectionNotString",
    "src/validator.js~Validator.isObjectOrCollectionNotString",
    "method"
  ],
  [
    "src/validator.js~validator.isstring",
    "class/src/validator.js~Validator.html#static-method-isString",
    "src/validator.js~Validator.isString",
    "method"
  ],
  [
    "src/validator.js~validator.isstringnotempty",
    "class/src/validator.js~Validator.html#static-method-isStringNotEmpty",
    "src/validator.js~Validator.isStringNotEmpty",
    "method"
  ],
  [
    "src/validator.js~validator.isuri",
    "class/src/validator.js~Validator.html#static-method-isURI",
    "src/validator.js~Validator.isURI",
    "method"
  ],
  [
    "src/validator.js~validator.isundefined",
    "class/src/validator.js~Validator.html#static-method-isUndefined",
    "src/validator.js~Validator.isUndefined",
    "method"
  ],
  [
    "src/validator.js~validator.isundefinedornull",
    "class/src/validator.js~Validator.html#static-method-isUndefinedOrNull",
    "src/validator.js~Validator.isUndefinedOrNull",
    "method"
  ],
  [
    "src/validator.js~validator.isversion",
    "class/src/validator.js~Validator.html#static-method-isVersion",
    "src/validator.js~Validator.isVersion",
    "method"
  ],
  [
    "test/cloudevent.test.js",
    "test-file/test/cloudevent.test.js.html",
    "test/cloudevent.test.js",
    "testFile"
  ],
  [
    "test/index.test.js",
    "test-file/test/index.test.js.html",
    "test/index.test.js",
    "testFile"
  ],
  [
    "test/transformer.test.js",
    "test-file/test/transformer.test.js.html",
    "test/transformer.test.js",
    "testFile"
  ],
  [
    "test/validator.test.js",
    "test-file/test/validator.test.js.html",
    "test/validator.test.js",
    "testFile"
  ]
]