window.esdocSearchIndex = [
  [
    "check-runtime-env/src/index.js~runtimeenvchecker",
    "class/src/index.js~RuntimeEnvChecker.html",
    "<span>RuntimeEnvChecker</span> <span class=\"search-result-import-path\">check-runtime-env/src/index.js</span>",
    "class"
  ],
  [
    "runtimeenvchecker src/index.js~runtimeenvchecker,runtimeenvchecker",
    "test-file/test/index.test.js.html#lineNumber196",
    "ensure generic utility methods works in the right way",
    "test"
  ],
  [
    "runtimeenvchecker src/index.js~runtimeenvchecker,runtimeenvchecker",
    "test-file/test/index.test.js.html#lineNumber31",
    "ensure objects exported by index script, exists and are of the right type",
    "test"
  ],
  [
    "runtimeenvchecker src/index.js~runtimeenvchecker,runtimeenvchecker",
    "test-file/test/index.test.js.html#lineNumber46",
    "ensure process info returns right values",
    "test"
  ],
  [
    "runtimeenvchecker src/index.js~runtimeenvchecker,runtimeenvchecker",
    "test-file/test/index.test.js.html#lineNumber220",
    "ensure utility methods on env vars works in the right way",
    "test"
  ],
  [
    "runtimeenvchecker src/index.js~runtimeenvchecker,runtimeenvchecker",
    "test-file/test/index.test.js.html#lineNumber57",
    "ensure version checks are done in the right way",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~runtimeenvchecker#constructor",
    "class/src/index.js~RuntimeEnvChecker.html#instance-constructor-constructor",
    "src/index.js~RuntimeEnvChecker#constructor",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.checkenvvardefined",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-checkEnvVarDefined",
    "src/index.js~RuntimeEnvChecker.checkEnvVarDefined",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.checknodeenvproduction",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-checkNodeEnvProduction",
    "src/index.js~RuntimeEnvChecker.checkNodeEnvProduction",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.checkstringnotempty",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-checkStringNotEmpty",
    "src/index.js~RuntimeEnvChecker.checkStringNotEmpty",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.checkversion",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-checkVersion",
    "src/index.js~RuntimeEnvChecker.checkVersion",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.checkversionofnode",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-checkVersionOfNode",
    "src/index.js~RuntimeEnvChecker.checkVersionOfNode",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.checkversionofnpm",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-checkVersionOfNpm",
    "src/index.js~RuntimeEnvChecker.checkVersionOfNpm",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.getnodeenv",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-getNodeEnv",
    "src/index.js~RuntimeEnvChecker.getNodeEnv",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.getversionofnpm",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-getVersionOfNpm",
    "src/index.js~RuntimeEnvChecker.getVersionOfNpm",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.isdefinedandnotnull",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-isDefinedAndNotNull",
    "src/index.js~RuntimeEnvChecker.isDefinedAndNotNull",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.isenvvardefined",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-isEnvVarDefined",
    "src/index.js~RuntimeEnvChecker.isEnvVarDefined",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.isnodeenvproduction",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-isNodeEnvProduction",
    "src/index.js~RuntimeEnvChecker.isNodeEnvProduction",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.isstringnotempty",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-isStringNotEmpty",
    "src/index.js~RuntimeEnvChecker.isStringNotEmpty",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.isversioncompatible",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-isVersionCompatible",
    "src/index.js~RuntimeEnvChecker.isVersionCompatible",
    "method"
  ],
  [
    "src/index.js~runtimeenvchecker.processinfo",
    "class/src/index.js~RuntimeEnvChecker.html#static-method-processInfo",
    "src/index.js~RuntimeEnvChecker.processInfo",
    "method"
  ],
  [
    "test/index.test.js",
    "test-file/test/index.test.js.html",
    "test/index.test.js",
    "testFile"
  ]
]